// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

function App$app(Props) {
  return React.createElement(ReactNative.View, {
              style: {
                alignItems: "center",
                flex: 1,
                justifyContent: "center"
              },
              children: React.createElement(ReactNative.Text, {
                    children: "Hello Rescript React Native!",
                    style: {
                      color: "#0284C7",
                      fontSize: 22
                    }
                  })
            });
}

var app = App$app;

export {
  app ,
  
}
/* react Not a pure module */
